// =============================================================================
// PresetLoadouts.sqf - preset loadouts (ACE / getUnitLoadout arrays for setUnitLoadout)
// =============================================================================
// missionNamespace FAC_presetLoadouts — compiled when player selects preset tab in Loadout GUI.
//
// Shape:
// [
//   [eraKey, eraDisplayName, [
//     [roleDisplayName, loadoutArray],
//     ...
//   ]],
//   ...
// ]
// - eraKey: no ":" (used in synthetic keys).
// - loadoutArray: getUnitLoadout / ACE export shape; must parse as valid SQF.
//   Must be exactly 10 array elements (0–9). Many ACE/ACEAX exports add an 11th slot
//   (e.g. aceax_textureOptions) — LoadoutGui truncates on apply; trim manually for clarity.
// =============================================================================

missionNamespace setVariable [
    "FAC_presetLoadouts",
    [
        [
            "modern",
            "2020s ADF RAR by MB",
            [
                [
                    "Platoon Commander",
                    [[["arifle_rho_ef88_cam4_F","","rho_rar_peq16b_wml_ir","rhsusf_acc_su230",["rho_rar_ef88_30Rnd_556x45_B_AUG",30],[],""],[],["ACWP_HP_ba","","","",["ACWP_13Rnd_9x21_Mag_HP_blk",13],[],""],["Rho_RAR_Combat_shirt_Tucked",[["ACE_fieldDressing",1],["ACE_quikclot",1],["ACE_tourniquet",1],["grad_paceCountBeads_functions_paceCountBeads",1],["kat_Painkiller",2,4],["acex_intelitems_notepad",1,1],["rho_rar_ef88_30Rnd_556x45_B_AUG",1,30]]],["rho_rar_vest_pl",[["ACE_IR_Strobe_Item",1],["ACRE_PRC343",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["kat_IFAK",1],["ACE_tourniquet",2],["kat_guedel",2],["kat_chestSeal",3],["ACE_elasticBandage",2],["ACE_packingBandage",2],["ACE_quikclot",2],["ACE_CableTie",4],["ItemcTabHCam",1],["ACE_splint",1],["ACE_bodyBag",2],["ACRE_PRC152",1],["ItemAndroid",1],["HandGrenade",3,1],["vn_m18_white_mag",2,1],["Chemlight_green",3,1],["Chemlight_red",3,1],["Chemlight_yellow",3,1],["acex_intelitems_notepad",1,1],["ACWP_13Rnd_9x21_Mag_HP_blk",2,13],["rho_rar_ef88_30Rnd_556x45_B_AUG",6,30]]],["ranger_pack_1",[["kat_IFAK",1],["ItemMicroDAGR",1],["Chemlight_green",3,1],["Chemlight_blue",3,1],["Chemlight_red",3,1],["Chemlight_yellow",3,1],["vn_m18_white_mag",2,1],["HandGrenade",2,1],["ACWP_13Rnd_9x21_Mag_HP_blk",3,13],["SmokeShellRed",1,1],["SmokeShellBlue",1,1],["SmokeShellYellow",1,1],["rho_rar_ef88_30Rnd_556x45_B_AUG",5,30]]],"rho_rar_tw_exfil2025_comtac_ir_bat","rho_reconwrap_03_glasses_blacklens",["ACE_VectorDay","","","",[],[],""],["ItemMap","","","ItemCompass","ItemWatch","USP_PVS31_WP_MID_BLK"]],[["ace_arsenal_insignia",""],["aceax_textureOptions",[]]]]
                ],
                [
                    "Sect Comd",
                    [[["arifle_rho_ef88_cam5_F","","rho_rar_peq16b_wml_ir","rhsusf_acc_su230",["rho_rar_ef88_30Rnd_556x45_B_AUG",30],[],""],[],["ACWP_HP_ba","","","",["ACWP_13Rnd_9x21_Mag_HP_blk",13],[],""],["Rho_RAR_Combat_shirt_Tucked",[["ACE_fieldDressing",1],["ACE_quikclot",1],["ACE_tourniquet",1],["grad_paceCountBeads_functions_paceCountBeads",1],["kat_Painkiller",2,4],["acex_intelitems_notepad",1,1],["rho_rar_ef88_30Rnd_556x45_B_AUG",1,30]]],["rho_rar_vest_secco",[["ACE_IR_Strobe_Item",1],["ACRE_PRC343",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["kat_IFAK",1],["ACE_tourniquet",2],["kat_guedel",2],["kat_chestSeal",3],["ACE_elasticBandage",2],["ACE_packingBandage",2],["ACE_quikclot",2],["ACE_CableTie",4],["ItemcTabHCam",1],["ACE_splint",1],["ACE_bodyBag",2],["ACRE_PRC152",1],["HandGrenade",3,1],["vn_m18_white_mag",2,1],["Chemlight_green",3,1],["Chemlight_red",3,1],["Chemlight_yellow",3,1],["acex_intelitems_notepad",1,1],["ACWP_13Rnd_9x21_Mag_HP_blk",2,13],["rho_rar_ef88_30Rnd_556x45_B_AUG",6,30]]],["ranger_pack_1",[["kat_IFAK",1],["ItemMicroDAGR",1],["Chemlight_green",3,1],["Chemlight_blue",3,1],["Chemlight_red",3,1],["Chemlight_yellow",3,1],["vn_m18_white_mag",2,1],["HandGrenade",2,1],["ACWP_13Rnd_9x21_Mag_HP_blk",3,13],["SmokeShellRed",1,1],["SmokeShellBlue",1,1],["SmokeShellYellow",1,1],["rho_rar_ef88_30Rnd_556x45_B_AUG",5,30]]],"rho_rar_tw_exfil2025_comtac_ir_bat","rho_reconwrap_03_glasses_blacklens",["ACE_VectorDay","","","",[],[],""],["ItemMap","","","ItemCompass","ItemWatch","USP_PVS31_WP_MID_BLK"]],[["ace_arsenal_insignia",""],["aceax_textureOptions",[]]]]
                ],
                [
                    "Sect 2IC",
                    [[["arifle_rho_ef88_cam2_F","","rho_rar_peq16b_wml_ir","rhsusf_acc_su230",["rho_rar_ef88_30Rnd_556x45_B_AUG",30],[],""],[],[],["Rho_RAR_Combat_shirt_Tucked",[["ACE_fieldDressing",1],["ACE_quikclot",1],["ACE_tourniquet",1],["grad_paceCountBeads_functions_paceCountBeads",1],["kat_Painkiller",2,4],["acex_intelitems_notepad",1,1]]],["rho_rar_vest_section2ic",[["ACE_IR_Strobe_Item",1],["ACRE_PRC343",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["kat_IFAK",1],["ACE_tourniquet",2],["kat_guedel",2],["kat_chestSeal",3],["ACE_elasticBandage",2],["ACE_packingBandage",2],["ACE_quikclot",2],["ACE_CableTie",4],["ItemcTabHCam",1],["ACE_splint",1],["ACE_bodyBag",2],["ACRE_PRC152",1],["HandGrenade",3,1],["vn_m18_white_mag",2,1],["Chemlight_green",3,1],["Chemlight_red",3,1],["Chemlight_yellow",3,1],["acex_intelitems_notepad",1,1],["rho_rar_ef88_30Rnd_556x45_B_AUG",7,30]]],["ranger_pack_1",[["kat_IFAK",1],["ItemMicroDAGR",1],["Chemlight_green",3,1],["Chemlight_blue",3,1],["Chemlight_red",3,1],["Chemlight_yellow",3,1],["vn_m18_white_mag",2,1],["HandGrenade",2,1],["rho_rar_ef88_30Rnd_556x45_B_AUG",5,30]]],"rho_rar_tw_exfil2025_comtac_ir_bat","rho_reconwrap_03_glasses_blacklens",["ACE_VectorDay","","","",[],[],""],["ItemMap","","","ItemCompass","ItemWatch","USP_PVS31_WP_MID_BLK"]],[["ace_arsenal_insignia",""],["aceax_textureOptions",[]]]]
                ],
                [
                    "SF",
                    [[["ACWP_M4A5_145_troy_Tango_DON","acwp_rc1_don","CUP_acc_ANPEQ_15_Flashlight_Black_L","acwp_eotech_don_g33_down",["ACWP_30rnd_556x45_EPR_PMAG_don",30],[],""],[],["75th_Ranger_G19","","75th_Ranger_x300u_1","75th_glock_rmr",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["Rho_RAR_Combat_shirt_Tucked_Bloused_Rolled_Coy_Gloves",[["ACE_fieldDressing",1],["ACE_quikclot",1],["ACE_tourniquet",1],["grad_paceCountBeads_functions_paceCountBeads",1],["kat_Painkiller",2,4],["acex_intelitems_notepad",1,1]]],["TFB_AVS_Assaulter_2_152A",[["ACE_IR_Strobe_Item",1],["ACRE_PRC343",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["kat_IFAK",1],["ACE_tourniquet",2],["kat_guedel",2],["kat_chestSeal",3],["ACE_elasticBandage",2],["ACE_packingBandage",2],["ACE_quikclot",2],["ACE_CableTie",4],["ItemcTabHCam",1],["ACE_splint",1],["ACRE_PRC152",1],["ACE_epinephrine",2],["ACE_morphine",2],["kat_atropine",2],["HandGrenade",3,1],["vn_m18_white_mag",2,1],["Chemlight_green",3,1],["Chemlight_red",3,1],["Chemlight_yellow",3,1],["acex_intelitems_notepad",1,1],["rhsusf_mag_17Rnd_9x19_JHP",3,17],["ACWP_30rnd_556x45_EPR_PMAG_don",7,30]]],["ranger_pack_1",[["kat_IFAK",1],["Chemlight_green",3,1],["Chemlight_blue",3,1],["Chemlight_red",3,1],["Chemlight_yellow",3,1],["vn_m18_white_mag",2,1],["HandGrenade",2,1]]],"rho_rar_airframe_ir_bat_comtac_mc","rho_reconwrap_03_glasses_blacklens",["ACE_VectorDay","","","",[],[],""],["ItemMap","","","ItemCompass","ItemWatch","USP_PVS31_WP_MID_BLK"]],[["ace_arsenal_insignia",""],["aceax_textureOptions",[]]]]
                ],
                [
                    "Medic",
                    [[["arifle_rho_ef88_cam7_F","","rho_rar_peq16b_wml_ir","rhsusf_acc_su230",["rho_rar_ef88_30Rnd_556x45_B_AUG",30],[],""],[],[],["Rho_RAR_Combat_shirt_Tucked",[["ACE_fieldDressing",1],["ACE_quikclot",1],["ACE_tourniquet",1],["grad_paceCountBeads_functions_paceCountBeads",1],["kat_Painkiller",2,4],["acex_intelitems_notepad",1,1]]],["rho_rar_vest_medic",[["ACE_IR_Strobe_Item",1],["ACRE_PRC343",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["kat_IFAK",1],["ACE_tourniquet",2],["kat_guedel",2],["kat_chestSeal",3],["ACE_elasticBandage",2],["ACE_packingBandage",2],["ACE_quikclot",2],["ACE_CableTie",4],["ItemcTabHCam",1],["ACE_splint",1],["HandGrenade",3,1],["vn_m18_white_mag",2,1],["Chemlight_green",3,1],["Chemlight_red",3,1],["Chemlight_yellow",3,1],["acex_intelitems_notepad",1,1],["rho_rar_ef88_30Rnd_556x45_B_AUG",7,30]]],["ranger_pack_3",[["ACE_Canteen",3],["ACE_MRE_LambCurry",1],["ACE_MRE_SteakVegetables",1],["kat_IFAK",1],["ACE_tourniquet",4],["ACE_salineIV",5],["ACE_splint",2],["kat_TXA",3],["kat_naloxone",4],["ACE_morphine",4],["kat_larynx",2],["kat_guedel",3],["kat_fentanyl",2],["kat_EACA",3],["kat_chestSeal",4],["ACE_bodyBag",4],["kat_accuvac",1],["kat_basicDiagnostic",1],["kat_AED",1],["kat_MFAK",1],["Chemlight_green",3,1],["Chemlight_blue",3,1],["Chemlight_red",3,1],["Chemlight_yellow",3,1],["vn_m18_white_mag",2,1],["HandGrenade",2,1],["kat_Penthrox",3,10],["ACE_painkillers",4,10],["rho_rar_ef88_30Rnd_556x45_B_AUG",5,30]]],"rho_rar_tw_exfil2025_comtac_ir_bat","rho_reconwrap_03_glasses_blacklens",["ACE_VectorDay","","","",[],[],""],["ItemMap","","","ItemCompass","ItemWatch","USP_PVS31_WP_MID_BLK"]],[["ace_arsenal_insignia",""],["aceax_textureOptions",[]]]]
                ],
                [
                    "Engineer",
                    [[["arifle_rho_ef88_cam4_F","","rho_rar_peq16b_wml_ir","rhsusf_acc_su230",["rho_rar_ef88_30Rnd_556x45_B_AUG",30],[],""],[],["121_serbu_breacher","","","",["121_2Rnd_Slug",2],[],""],["Rho_RAR_Combat_shirt_Tucked",[["ACE_fieldDressing",1],["ACE_quikclot",1],["ACE_tourniquet",1],["grad_paceCountBeads_functions_paceCountBeads",1],["ACE_MapTools",1],["ACE_splint",1],["kat_Painkiller",2,4],["acex_intelitems_notepad",2,1]]],["rho_rar_vest_engi",[["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["kat_IFAK",1],["ACE_tourniquet",2],["kat_guedel",2],["kat_chestSeal",3],["ACE_elasticBandage",2],["ACE_packingBandage",2],["ACE_quikclot",2],["ACE_CableTie",4],["ACRE_PRC343",1],["tsp_breach_shock",3],["ItemcTabHCam",1],["HandGrenade",3,1],["Chemlight_green",6,1],["Chemlight_red",6,1],["Chemlight_yellow",6,1],["Chemlight_blue",3,1],["rho_rar_ef88_30Rnd_556x45_B_AUG",5,30]]],["ranger_pack_5",[["ACE_DefusalKit",1],["ACE_wirecutter",1],["kat_IFAK",1],["ACE_EntrenchingTool",1],["MineDetector",1],["tsp_breach_block_mag",3,1],["tsp_breach_silhouette_mag",1,1],["tsp_breach_stick_mag",4,1],["tsp_breach_linear_mag",3,1],["tsp_breach_popper_mag",3,1],["rho_rar_ef88_30Rnd_556x45_B_AUG",2,30]]],"rho_rar_tw_exfil2025_comtac_ir_bat","rho_reconwrap_03_glasses_blacklens",["ACE_VectorDay","","","",[],[],""],["ItemMap","","","ItemCompass","ItemWatch","USP_PVS31_WP_MID_BLK"]],[["ace_arsenal_insignia","_alt"],["aceax_textureOptions",[]]]]
                ],
                [
                    "JTAC",
                    [[["arifle_rho_ef88_cam9_F","","rho_rar_peq16b_wml_ir","rhsusf_acc_su230",["rho_rar_ef88_30Rnd_556x45_B_AUG",30],[],""],[],[],["Rho_RAR_Combat_shirt_Tucked",[["ACE_fieldDressing",1],["ACE_quikclot",1],["ACE_tourniquet",1],["grad_paceCountBeads_functions_paceCountBeads",1],["ACE_artilleryTable",1],["ItemMicroDAGR",1],["ACE_ATragMX",1],["ACE_RangeCard",1],["ACE_PlottingBoard",1],["USP_PVS31_WP_MID_BLK",1],["kat_Painkiller",2,4],["acex_intelitems_notepad",1,1]]],["rho_rar_vest_fo",[["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["kat_IFAK",1],["ACE_tourniquet",2],["kat_guedel",2],["kat_chestSeal",3],["ACE_elasticBandage",2],["ACE_packingBandage",2],["ACE_quikclot",2],["ACE_CableTie",4],["ItemcTabHCam",1],["ACE_splint",1],["ACRE_PRC343",1],["ACRE_PRC152",1],["HandGrenade",3,1],["vn_m18_white_mag",2,1],["Chemlight_green",3,1],["Chemlight_red",3,1],["Chemlight_yellow",3,1],["acex_intelitems_notepad",1,1],["rho_rar_ef88_30Rnd_556x45_B_AUG",7,30],["SmokeShellBlue",1,1],["SmokeShellGreen",1,1],["SmokeShellPurple",1,1],["SmokeShellRed",1,1],["SmokeShellYellow",1,1]]],["TFB_275_117G3",[["ACRE_PRC117F",1],["SmokeShellGreen",6,1],["SmokeShellRed",8,1],["SmokeShellPurple",6,1]]],"rho_rar_boonie_04","rho_reconwrap_03_glasses_blacklens",["ACE_VectorDay","","","",[],[],""],["ItemMap","","","ItemCompass","ItemWatch",""]],[["ace_arsenal_insignia","_alt"],["aceax_textureOptions",[]]]]
                ],
                [
                    "Rifleman",
                    [[["arifle_rho_ef88_cam10_F","","rho_rar_peq16b_wml_ir","rhsusf_acc_su230",["rho_rar_ef88_30Rnd_556x45_B_AUG",30],[],""],[],[],["Rho_RAR_Combat_shirt_Tucked",[["ACE_fieldDressing",1],["ACE_quikclot",1],["ACE_tourniquet",1],["grad_paceCountBeads_functions_paceCountBeads",1],["kat_Painkiller",2,4],["acex_intelitems_notepad",1,1]]],["rho_rar_vest_rifle",[["ACE_IR_Strobe_Item",1],["ACRE_PRC343",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["kat_IFAK",1],["ACE_tourniquet",2],["kat_guedel",2],["kat_chestSeal",3],["ACE_elasticBandage",2],["ACE_packingBandage",2],["ACE_quikclot",2],["ACE_CableTie",4],["ItemcTabHCam",1],["ACE_splint",1],["HandGrenade",3,1],["vn_m18_white_mag",2,1],["Chemlight_green",3,1],["Chemlight_red",3,1],["Chemlight_yellow",3,1],["acex_intelitems_notepad",1,1],["rho_rar_ef88_30Rnd_556x45_B_AUG",7,30]]],["ranger_pack_1",[["kat_IFAK",1],["Chemlight_green",3,1],["Chemlight_blue",3,1],["Chemlight_red",3,1],["Chemlight_yellow",3,1],["vn_m18_white_mag",2,1],["HandGrenade",2,1],["rho_rar_ef88_30Rnd_556x45_B_AUG",5,30]]],"rho_rar_tw_exfil2025_comtac_ir_bat","rho_reconwrap_03_glasses_blacklens",["ACE_VectorDay","","","",[],[],""],["ItemMap","","","ItemCompass","ItemWatch","USP_PVS31_WP_MID_BLK"]],[["ace_arsenal_insignia","_alt"],["aceax_textureOptions",[]]]]
                ],
                [
                    "Grenadier",
                    [[["arifle_rho_ef88_GL_cam9_F","","rho_rar_peq16b_wml_ir","rhsusf_acc_su230",["rho_rar_ef88_30Rnd_556x45_B_AUG",30],["1Rnd_HE_Grenade_shell",1],""],[],[],["Rho_RAR_Combat_shirt_Tucked",[["ACE_fieldDressing",1],["ACE_quikclot",1],["ACE_tourniquet",1],["grad_paceCountBeads_functions_paceCountBeads",1],["kat_Painkiller",2,4],["acex_intelitems_notepad",1,1]]],["rho_rar_vest_grenadier",[["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["kat_IFAK",1],["ACE_tourniquet",2],["kat_guedel",2],["kat_chestSeal",3],["ACE_elasticBandage",2],["ACE_packingBandage",2],["ACE_quikclot",2],["ACE_CableTie",4],["ItemcTabHCam",1],["ACE_splint",1],["ACRE_PRC343",1],["HandGrenade",1,1],["Chemlight_green",3,1],["Chemlight_red",3,1],["Chemlight_yellow",3,1],["acex_intelitems_notepad",1,1],["rho_rar_ef88_30Rnd_556x45_B_AUG",7,30],["1Rnd_HE_Grenade_shell",7,1],["rhs_mag_m714_White",3,1],["rhs_mag_m716_yellow",1,1],["rhs_mag_m713_Red",1,1]]],["ranger_pack_1",[["kat_IFAK",1],["Chemlight_green",3,1],["Chemlight_blue",3,1],["Chemlight_red",3,1],["Chemlight_yellow",3,1],["vn_m18_white_mag",2,1],["HandGrenade",2,1],["rho_rar_ef88_30Rnd_556x45_B_AUG",5,30],["1Rnd_HE_Grenade_shell",5,1],["1Rnd_Smoke_Grenade_shell",3,1]]],"rho_rar_tw_exfil2025_comtac_ir_bat","rho_reconwrap_03_glasses_blacklens",["ACE_VectorDay","","","",[],[],""],["ItemMap","","","ItemCompass","ItemWatch","USP_PVS31_WP_MID_BLK"]],[["ace_arsenal_insignia","_alt"],["aceax_textureOptions",[]]]]
                ],
                [
                    "Marksman",
                    [[["CUP_arifle_HK417_20_Wood","","","CUP_optic_ACOG_TA648_308_RDS_od",["CUP_20Rnd_762x51_HK417_Camo_Wood",20],[],""],[],[],["Rho_RAR_Combat_shirt_Tucked",[["ACE_fieldDressing",1],["ACE_quikclot",1],["ACE_tourniquet",1],["grad_paceCountBeads_functions_paceCountBeads",1],["kat_Painkiller",2,4],["acex_intelitems_notepad",1,1]]],["rho_rar_vest_rifle",[["ACE_IR_Strobe_Item",1],["ACRE_PRC343",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["kat_IFAK",1],["ACE_tourniquet",2],["kat_guedel",2],["kat_chestSeal",3],["ACE_elasticBandage",2],["ACE_packingBandage",2],["ACE_quikclot",2],["ACE_CableTie",4],["ItemcTabHCam",1],["ACE_splint",1],["HandGrenade",3,1],["vn_m18_white_mag",2,1],["Chemlight_green",3,1],["Chemlight_red",3,1],["Chemlight_yellow",3,1],["acex_intelitems_notepad",1,1],["CUP_20Rnd_762x51_HK417_Camo_Wood",5,20]]],["ranger_pack_1",[["ACE_Canteen",3],["kat_IFAK",1],["Chemlight_green",3,1],["Chemlight_blue",3,1],["Chemlight_red",3,1],["Chemlight_yellow",3,1],["vn_m18_white_mag",2,1],["HandGrenade",2,1]]],"rho_rar_tw_exfil2025_comtac_ir_bat","rho_reconwrap_03_glasses_blacklens",["ACE_VectorDay","","","",[],[],""],["ItemMap","","","ItemCompass","ItemWatch","USP_PVS31_WP_MID_BLK"]],[["ace_arsenal_insignia","_alt"],["aceax_textureOptions",[]]]]
                ],
                [
                    "Minimi Gunner",
                    [[["rhs_weap_m249_pip","","","TFB_elcan_su230",["rhsusf_100Rnd_556x45_M855_soft_pouch_coyote",100],[],"rhsusf_acc_saw_bipod"],[],[],["Rho_RAR_Combat_shirt_Tucked",[["ACE_fieldDressing",1],["ACE_quikclot",1],["ACE_tourniquet",1],["grad_paceCountBeads_functions_paceCountBeads",1],["kat_Painkiller",2,4],["acex_intelitems_notepad",1,1]]],["rho_rar_vest_lmg",[["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["kat_IFAK",1],["ACE_tourniquet",2],["kat_guedel",2],["kat_chestSeal",3],["ACE_elasticBandage",2],["ACE_packingBandage",2],["ACE_quikclot",2],["ACE_CableTie",4],["ItemcTabHCam",1],["ACE_splint",1],["ACRE_PRC343",1],["vn_m18_white_mag",2,1],["Chemlight_green",3,1],["Chemlight_red",3,1],["Chemlight_yellow",3,1],["acex_intelitems_notepad",1,1],["200Rnd_556x45_Box_F",1,200],["rhsusf_100Rnd_556x45_M855_mixed_soft_pouch_coyote",2,100]]],["ranger_pack_1",[["ACE_Canteen",3],["kat_IFAK",1],["Chemlight_green",3,1],["Chemlight_blue",3,1],["Chemlight_red",3,1],["Chemlight_yellow",3,1],["vn_m18_white_mag",2,1],["HandGrenade",2,1],["rhsusf_100Rnd_556x45_M855_mixed_soft_pouch_coyote",4,100]]],"rho_rar_tw_exfil2025_comtac_ir_bat","rho_reconwrap_03_glasses_blacklens",["ACE_VectorDay","","","",[],[],""],["ItemMap","","","ItemCompass","ItemWatch","USP_PVS31_WP_MID_BLK"]],[["ace_arsenal_insignia","_alt"],["aceax_textureOptions",[]]]]
                ],
                [
                    "Mag58 Gunner",
                    [[["rhs_weap_fnmag","","","TFB_elcan_su230",["rhsusf_100Rnd_762x51",100],[],""],[],[],["Rho_RAR_Combat_shirt_Tucked",[["ACE_fieldDressing",1],["ACE_quikclot",1],["ACE_tourniquet",1],["grad_paceCountBeads_functions_paceCountBeads",1],["kat_Painkiller",2,4],["acex_intelitems_notepad",1,1]]],["rho_rar_vest_mg",[["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["kat_IFAK",1],["ACE_tourniquet",2],["kat_guedel",2],["kat_chestSeal",3],["ACE_elasticBandage",2],["ACE_packingBandage",2],["ACE_quikclot",2],["ACE_CableTie",4],["ItemcTabHCam",1],["ACE_splint",1],["ACRE_PRC343",1],["vn_m18_white_mag",2,1],["Chemlight_green",3,1],["Chemlight_red",3,1],["Chemlight_yellow",3,1],["acex_intelitems_notepad",1,1],["rhsusf_100Rnd_762x51",4,100]]],["ranger_pack_1",[["ACE_Canteen",3],["kat_IFAK",1],["Chemlight_green",3,1],["Chemlight_blue",3,1],["Chemlight_red",3,1],["Chemlight_yellow",3,1],["vn_m18_white_mag",2,1],["HandGrenade",2,1],["rhsusf_100Rnd_762x51",4,100]]],"rho_rar_tw_exfil2025_comtac_ir_bat","rho_reconwrap_03_glasses_blacklens",["ACE_VectorDay","","","",[],[],""],["ItemMap","","","ItemCompass","ItemWatch","USP_PVS31_WP_MID_BLK"]],[["ace_arsenal_insignia","_alt"],["aceax_textureOptions",[]]]]
                ],
                [
                    "Asst Machinegunner",
                    [[["arifle_rho_ef88_cam7_F","","rho_rar_peq16b_wml_ir","rhsusf_acc_su230",["rho_rar_ef88_30Rnd_556x45_B_AUG",30],[],""],[],[],["Rho_RAR_Combat_shirt_Tucked",[["ACE_fieldDressing",1],["ACE_quikclot",1],["ACE_tourniquet",1],["grad_paceCountBeads_functions_paceCountBeads",1],["kat_Painkiller",2,4],["acex_intelitems_notepad",1,1]]],["rho_rar_vest_rifle2",[["ACE_IR_Strobe_Item",1],["ACRE_PRC343",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["kat_IFAK",1],["ACE_tourniquet",2],["kat_guedel",2],["kat_chestSeal",3],["ACE_elasticBandage",2],["ACE_packingBandage",2],["ACE_quikclot",2],["ACE_CableTie",4],["ItemcTabHCam",1],["ACE_splint",1],["HandGrenade",3,1],["vn_m18_white_mag",2,1],["Chemlight_green",3,1],["Chemlight_red",3,1],["Chemlight_yellow",3,1],["acex_intelitems_notepad",1,1],["rho_rar_ef88_30Rnd_556x45_B_AUG",7,30]]],["ranger_pack_1",[["ACE_Canteen",3],["kat_IFAK",1],["Chemlight_green",3,1],["Chemlight_blue",3,1],["Chemlight_red",3,1],["Chemlight_yellow",3,1],["vn_m18_white_mag",2,1],["HandGrenade",2,1],["rhsusf_100Rnd_556x45_M855_soft_pouch_coyote",5,100],["rho_rar_ef88_30Rnd_556x45_B_AUG",5,30]]],"rho_rar_tw_exfil2025_comtac_ir_bat","rho_reconwrap_03_glasses_blacklens",["ACE_VectorDay","","","",[],[],""],["ItemMap","","","ItemCompass","ItemWatch","USP_PVS31_WP_MID_BLK"]],[["ace_arsenal_insignia","_alt"],["aceax_textureOptions",[]]]]
                ],
                [
                    "Sniper",
                    [[["ACWP_blaser_r93_don","muzzle_snds_338_black","","TFB_ATACR",["ACWP_5rnd_338LM_base",5],[],"bipod_01_F_blk"],[],["ACWP_HP_ba","","","",["ACWP_13Rnd_9x21_Mag_HP_blk",13],[],""],["UK3CB_ANA_B_U_CombatUniform_Ghillie_GCAM",[["ACE_fieldDressing",1],["ACE_quikclot",1],["ACE_tourniquet",1],["grad_paceCountBeads_functions_paceCountBeads",1],["kat_Painkiller",2,4],["acex_intelitems_notepad",1,1],["ACWP_5rnd_338LM_base",2,5]]],["TFB_AVS_Light_2_152A",[["ACE_IR_Strobe_Item",1],["ACRE_PRC343",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["kat_IFAK",1],["ACE_tourniquet",2],["kat_guedel",2],["kat_chestSeal",3],["ACE_elasticBandage",2],["ACE_packingBandage",2],["ACE_quikclot",2],["ACE_CableTie",4],["ItemcTabHCam",1],["ACE_splint",1],["ACRE_PRC152",1],["ACE_ATragMX",1],["ACE_Kestrel4500",1],["ItemMicroDAGR",1],["HandGrenade",3,1],["vn_m18_white_mag",2,1],["Chemlight_green",3,1],["Chemlight_red",3,1],["Chemlight_yellow",3,1],["acex_intelitems_notepad",1,1],["ACWP_5rnd_338LM_APDS",5,5],["ACWP_13Rnd_9x21_Mag_HP_blk",2,13],["ACWP_5rnd_338LM_base",4,5]]],["ranger_pack_1",[["kat_IFAK",1],["Chemlight_green",3,1],["Chemlight_blue",3,1],["Chemlight_red",3,1],["Chemlight_yellow",3,1],["vn_m18_white_mag",2,1],["HandGrenade",2,1],["ACWP_5rnd_338LM_base",1,5]]],"","",["ACE_VectorDay","","","",[],[],""],["ItemMap","","","ItemCompass","ItemWatch",""]],[["ace_arsenal_insignia","_alt"],["aceax_textureOptions",[]]]]
                ],
                [
                    "Pilot",
                    [[["arifle_rho_ef88_C_blk_F","","rho_rar_peq16b_wml_ir","rhsusf_acc_su230",["rho_rar_ef88_30Rnd_556x45_B_AUG",30],[],""],[],["ACWP_HP_ba","","","",["ACWP_13Rnd_9x21_Mag_HP_blk",13],[],""],["SOAR_Flight_3_uniform",[["ACE_fieldDressing",1],["ACE_quikclot",1],["ACE_tourniquet",1],["grad_paceCountBeads_functions_paceCountBeads",1],["kat_Painkiller",2,4],["acex_intelitems_notepad",1,1]]],["rho_rar_vest_pl",[["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["kat_IFAK",1],["ACE_tourniquet",2],["kat_guedel",2],["kat_chestSeal",3],["ACE_elasticBandage",2],["ACE_packingBandage",2],["ACE_quikclot",2],["ACE_CableTie",4],["ItemcTabHCam",1],["ACE_splint",1],["ItemAndroid",1],["ACRE_PRC152",1],["vn_m18_white_mag",2,1],["acex_intelitems_notepad",1,1],["rho_rar_ef88_30Rnd_556x45_B_AUG",7,30],["SmokeShellBlue",1,1],["SmokeShellRed",1,1]]],[],"rhsusf_hgu56p_visor_mask","rho_reconwrap_03_glasses_blacklens",["ACE_VectorDay","","","",[],[],""],["ItemMap","","","ItemCompass","ItemWatch","USP_PVS31_WP_MID_BLK"]],[["ace_arsenal_insignia",""],["aceax_textureOptions",[]]]]
                ]
            ]
        ],
        [
            "2000sUSMC",
            "2000s USMC by Crusty",
            [
                [
                    "Medic",
                    [[["simc_m4a0_erla","","","simc_optic_m2_low_lens",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],""],[],[],["U_simc_DCU_03_knee_nomex_trop",[["kat_IFAK",1],["ACE_EarPlugs",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1]]],["V_Simc_IBA_M81_lbv_mk2_2",[["rhs_mag_m67",2,1],["SmokeShell",2,1],["rhs_mag_30Rnd_556x45_M855A1_Stanag",8,30]]],["B_simc_US_Molle_Medic_m81",[["kat_MFAK",1],["ACE_surgicalKit",1],["kat_accuvac",1]]],"H_Simc_pasgt_DCU_TASC_b_nvo_strap_X800","G_simc_peltor",[],["ItemMap","","","ItemCompass","ItemWatch",""]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "Demolition",
                    [[["simc_m4a0_erla","","","simc_optic_m2_low",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],""],[],[],["U_simc_DCU_03_gas_knee_nomex_trop",[["kat_IFAK",1],["ACE_EarPlugs",1],["iedd_item_notebook",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1]]],["V_Simc_IBA_M81_1",[["ACE_M26_Clacker",1],["ACE_DefusalKit",1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["rhs_mag_30Rnd_556x45_M855A1_Stanag",8,30]]],["B_simc_US_Molle_patrol_m81",[["rhsusf_m112x4_mag",1,1],["rhsusf_m112_mag",2,1],["SatchelCharge_Remote_Mag",1,1]]],"H_Simc_pasgt_DCU_b_nvo_ESS","G_simc_peltor",[],["ItemMap","","","ItemCompass","ItemWatch",""]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "Machine Gunner",
                    [[["UK3CB_M60","","","",["UK3CB_M60_100rnd_762x51_GM",100],[],""],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["U_simc_DCU_03_eto_gas_knee",[["kat_IFAK",1],["ACE_EarPlugs",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1]]],["V_Simc_IBA_M81_erla_MG_2",[["rhs_mag_m67",2,1],["SmokeShell",2,1],["rhsusf_mag_15Rnd_9x19_JHP",2,15],["UK3CB_M60_100rnd_762x51_GM",4,100]]],[],"H_Simc_pasgt_DCU_nvo_X800","G_simc_peltor",[],["ItemMap","","","ItemCompass","ItemWatch",""]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "Machine Gun Assistant",
                    [[["UK3CB_M60","","","",["UK3CB_M60_100rnd_762x51_GM",100],[],""],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["U_simc_DCU_03_eto_gas_knee",[["kat_IFAK",1],["ACE_EarPlugs",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1]]],["V_Simc_IBA_M81_erla_MG_2",[["rhs_mag_m67",2,1],["SmokeShell",2,1],["rhsusf_mag_15Rnd_9x19_JHP",2,15],["UK3CB_M60_100rnd_762x51_GM",4,100]]],[],"H_Simc_pasgt_DCU_nvo_X800","G_simc_peltor",[],["ItemMap","","","ItemCompass","ItemWatch",""]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "Rifleman",
                    [[["simc_m4a0_erla","","","simc_optic_m2_low",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],""],[],[],["U_simc_DCU_03_alt_knee",[["kat_IFAK",1],["ACE_EarPlugs",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1]]],["V_Simc_IBA_M81_1",[["rhs_mag_m67",2,1],["SmokeShell",2,1],["rhs_mag_30Rnd_556x45_M855A1_Stanag",8,30]]],[],"H_Simc_pasgt_dcu_SWDG_nvo_b_low","",[],["ItemMap","","","ItemCompass","ItemWatch",""]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "Rifleman M136",
                    [[["simc_m4a0_erla","","","simc_optic_m2_low",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],""],["rhs_weap_M136","","rhs_acc_at4_handler","",[],[],""],[],["U_simc_DCU_03_alt_knee",[["kat_IFAK",1],["ACE_EarPlugs",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1]]],["V_Simc_IBA_M81_1",[["rhs_mag_m67",2,1],["SmokeShell",2,1],["rhs_mag_30Rnd_556x45_M855A1_Stanag",8,30]]],[],"H_Simc_pasgt_dcu_SWDG_nvo_b_low","",[],["ItemMap","","","ItemCompass","ItemWatch",""]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "Rifleman SMAW",
                    [[["simc_m4a0_erla","","","simc_optic_m2_low",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],""],["rhs_weap_smaw_green","","","",["rhs_mag_smaw_HEAA",1],[],""],[],["U_simc_DCU_03_alt_knee",[["kat_IFAK",1],["ACE_EarPlugs",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1]]],["V_Simc_IBA_M81_1",[["rhs_mag_m67",2,1],["SmokeShell",2,1],["rhs_mag_30Rnd_556x45_M855A1_Stanag",8,30]]],[],"H_Simc_pasgt_dcu_SWDG_nvo_b_low","",[],["ItemMap","","","ItemCompass","ItemWatch",""]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "Rifleman SMAW Assistant",
                    [[["simc_m4a0_erla","","","simc_optic_m2_low",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],""],[],[],["U_simc_DCU_03_alt_knee",[["kat_IFAK",1],["ACE_EarPlugs",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1]]],["V_Simc_IBA_M81_1",[["rhs_mag_m67",2,1],["SmokeShell",2,1],["rhs_mag_30Rnd_556x45_M855A1_Stanag",8,30]]],["B_simc_pack_alice_M81_frame_1",[]],"H_Simc_pasgt_dcu_SWDG_nvo_b_low","",[],["ItemMap","","","ItemCompass","ItemWatch",""]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "Grenadier",
                    [[["simc_m4a0_LMT_gl","","","simc_optic_m2_low_rear_lens",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],["1Rnd_HE_Grenade_shell",1],""],[],[],["U_simc_DCU_03_alt_knee",[["kat_IFAK",1],["ACE_EarPlugs",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1]]],["V_Simc_IBA_M81_flc_erla_4cm_2",[["rhs_mag_m67",2,1],["SmokeShell",2,1],["rhs_mag_30Rnd_556x45_M855A1_Stanag",8,30],["1Rnd_HE_Grenade_shell",10,1]]],[],"H_Simc_pasgt_dcu_TASC_nvo","G_LEN_TG1_weiss",[],["ItemMap","","","ItemCompass","ItemWatch",""]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "Squad Leader",
                    [[["simc_m4a0_ras_LMT_VFG","","","simc_optic_m2_low",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],""],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["U_simc_DCU_03_alt_knee",[["kat_IFAK",1],["ACE_EarPlugs",1],["ACRE_PRC343",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["acex_intelitems_notepad",1,1]]],["V_Simc_IBA_M81_45_1",[["ACRE_PRC148",1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["rhsusf_mag_15Rnd_9x19_JHP",2,15],["rhs_mag_30Rnd_556x45_M855A1_Stanag",8,30]]],[],"H_Simc_pasgt_DCU_nvo_strap_X800","",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ItemWatch",""]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "Light Machine Gunner",
                    [[["rhs_weap_m249_pip","","","",["rhsusf_200rnd_556x45_mixed_box",200],[],"rhsusf_acc_saw_bipod"],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["U_simc_DCU_03_eto_gas_knee",[["kat_IFAK",1],["ACE_EarPlugs",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1]]],["V_Simc_IBA_M81_erla_MG_2",[["rhs_mag_m67",2,1],["SmokeShell",2,1],["rhsusf_mag_15Rnd_9x19_JHP",2,15],["rhsusf_200rnd_556x45_mixed_box",3,200]]],[],"H_Simc_pasgt_DCU_nvo_X800","G_simc_peltor",[],["ItemMap","","","ItemCompass","ItemWatch",""]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "JFO",
                    [[["simc_m4a0_LMT_gl","","","simc_optic_m2_low_rear_lens",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],["1Rnd_HE_Grenade_shell",1],""],[],[],["U_simc_DCU_03_alt_knee",[["kat_IFAK",1],["ACE_EarPlugs",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACRE_PRC148",1]]],["V_Simc_IBA_M81_flc_erla_4cm_2",[["rhs_mag_m67",2,1],["SmokeShell",2,1],["rhs_mag_30Rnd_556x45_M855A1_Stanag",8,30],["1Rnd_HE_Grenade_shell",4,1],["1Rnd_SmokeRed_Grenade_shell",6,1],["SmokeShellBlue",2,1],["SmokeShellGreen",2,1],["SmokeShellRed",2,1]]],["B_simc_US_Molle_Patrol_m81_RTO_wasser",[["ACRE_PRC117F",1]]],"H_Simc_pasgt_dcu_TASC_nvo","G_LEN_TG1_weiss",["rhsusf_bino_lrf_Vector21","","","",[],[],""],["ItemMap","","","ItemCompass","ItemWatch",""]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "Crewman",
                    [[["simc_m4a0_erla","","","",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],""],[],[],["U_simc_DCU_03_alt_knee",[["kat_IFAK",1],["ACE_EarPlugs",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1]]],["V_Simc_IBA_M81_1",[["rhs_mag_m67",2,1],["SmokeShell",2,1],["rhs_mag_30Rnd_556x45_M855A1_Stanag",8,30]]],[],"cvc_g","",[],["ItemMap","","","ItemCompass","ItemWatch",""]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "Rifleman Javelin",
                    [[["simc_m4a0_erla","","","simc_optic_m2_low",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],""],["rhs_weap_fgm148","","","",["rhs_fgm148_magazine_AT",1],[],""],[],["U_simc_DCU_03_alt_knee",[["kat_IFAK",1],["ACE_EarPlugs",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1]]],["V_Simc_IBA_M81_1",[["rhs_mag_m67",2,1],["SmokeShell",2,1],["rhs_mag_30Rnd_556x45_M855A1_Stanag",8,30]]],[],"H_Simc_pasgt_dcu_SWDG_nvo_b_low","",[],["ItemMap","","","ItemCompass","ItemWatch",""]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "Rifleman Javelin Assistant",
                    [[["simc_m4a0_erla","","","simc_optic_m2_low",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],""],[],[],["U_simc_DCU_03_alt_knee",[["kat_IFAK",1],["ACE_EarPlugs",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1]]],["V_Simc_IBA_M81_1",[["rhs_mag_m67",2,1],["SmokeShell",2,1],["rhs_mag_30Rnd_556x45_M855A1_Stanag",8,30]]],["UK3CB_B_Alice_pack_01",[]],"H_Simc_pasgt_dcu_b_nvo_swdg","",[],["ItemMap","","","ItemCompass","ItemWatch",""]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "Breacher",
                    [[["simc_m4a0_erla","","","simc_optic_m2_low",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],""],[],[],["U_simc_DCU_03_alt_knee",[["kat_IFAK",1],["ACE_EarPlugs",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1]]],["V_Simc_IBA_M81_1",[["rhs_mag_m67",2,1],["SmokeShell",2,1],["rhs_mag_30Rnd_556x45_M855A1_Stanag",8,30]]],["B_simc_US_Molle_sturm_m81_etool",[["tsp_breach_linear_mag",3,1],["tsp_breach_silhouette_mag",1,1],["tsp_breach_package_mag",1,1]]],"H_Simc_pasgt_dcu_b_nvo_strap","UK3CB_G_Ballistic_Shemagh_Tan_Gloves_Tan",[],["ItemMap","","","ItemCompass","ItemWatch",""]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "Marksman",
                    [[["rhs_weap_m14_rail","rhsusf_acc_m14_flashsuppresor","","rhsusf_acc_LEUPOLDMK4",["20Rnd_762x51_Mag",20],[],""],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["U_simc_DCU_03_alt_knee",[["kat_IFAK",1],["ACE_EarPlugs",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["rhsusf_20Rnd_762x51_m80_Mag",1,20]]],["V_Simc_IBA_M81_1",[["rhs_mag_m67",2,1],["SmokeShell",2,1],["rhsusf_mag_15Rnd_9x19_JHP",2,15],["rhsusf_20Rnd_762x51_m80_Mag",6,20]]],[],"H_Simc_pasgt_dcu_b_nvo_strap_swdg","UK3CB_G_Ballistic_Shemagh_White_Tactical_Gloves_Green",[],["ItemMap","","","ItemCompass","ItemWatch",""]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "Sniper",
                    [[["rhs_weap_m40a5","","","rhsusf_acc_LEUPOLDMK4",["rhsusf_5Rnd_762x51_AICS_m118_special_Mag",5],[],"rhsusf_acc_harris_swivel"],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["U_simc_DCU_03_alt_gas_knee",[["kat_IFAK",1],["ACE_EarPlugs",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACE_RangeCard",1],["ACE_EntrenchingTool",1],["ACRE_PRC148",1]]],["V_Simc_IBA_M81_4",[["rhs_mag_m67",2,1],["SmokeShell",2,1],["rhsusf_mag_15Rnd_9x19_JHP",6,15],["rhsusf_5Rnd_762x51_AICS_m118_special_Mag",14,5]]],[],"H_Simc_pasgt_dcu_b_nvo_strap_swdg","UK3CB_G_Tactical_Clear_Shemagh_Tan_Gloves_Green",[],["ItemMap","","","ItemCompass","ItemWatch",""]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "Spotter",
                    [[["simc_m4a0_erla","","","rhsusf_acc_ACOG_3d",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],""],[],[],["U_simc_DCU_03_alt_knee",[["kat_IFAK",1],["ACE_EarPlugs",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACE_RangeCard",1],["acex_intelitems_notepad",1,1]]],["V_Simc_IBA_M81_1",[["rhs_mag_m67",2,1],["SmokeShell",2,1],["rhs_mag_30Rnd_556x45_M855A1_Stanag",8,30]]],["B_simc_US_Molle_sturm_m81",[["ACE_SpottingScope",1],["ACE_Tripod",1],["ACE_EntrenchingTool",1]]],"H_Simc_pasgt_dcu_TASC_nvo_strap","",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ItemWatch",""]],[["aceax_textureOptions",[]]]]
                ]
            ]
        ],
        [
            "jtacJoon",
            "JTAC by Joon",
            [
                [
                    "Modern",
                    [[["rhs_weap_m4a1_blockII_d","","","Tier1_Shortdot_Geissele_Docter_Desert",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],""],[],["rhs_weap_M320","","","",["rhs_mag_M441_HE",1],[],""],["U_tweed_acu_summer_ocp_blench_crye_knee",[["ACE_fieldDressing",8],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_tourniquet",2],["ACE_packingBandage",2],["ACE_elasticBandage",2],["ACE_IR_Strobe_Item",1]]],["tfa_v_mmac_teamleader_belt_coy",[["ACRE_PRC152",1],["ACRE_PRC343",1],["rhs_mag_m18_green",3,1],["rhs_mag_m18_purple",3,1],["SmokeShellRed",3,1],["SmokeShellOrange",2,1],["rhs_mag_30Rnd_556x45_M855_Stanag_Pull_Tracer_Red",5,30]]],["CUP_B_USPack_Coyote",[["ACRE_PRC152",1],["ACRE_PRC343",1],["kat_IFAK",1],["ACRE_PRC117F",1],["SmokeShellGreen",7,1],["SmokeShellOrange",3,1],["SmokeShellRed",6,1],["SmokeShellPurple",5,1],["SmokeShellBlue",4,1],["SmokeShellYellow",2,1]]],"SOTG_Helmets_8","G_Bandanna_khk",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","","ItemCompass","ItemWatch",""]],[]]
                ],
                [
                    "Night Fighting",
                    [[["rhs_weap_m4a1_blockII_M203_d","","","rhsusf_acc_su230_mrds_c",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],["1Rnd_SmokeRed_Grenade_shell",1],""],[],["rhs_weap_M320","","","",["rhs_mag_M441_HE",1],[],""],["U_tweed_acu_summer_ocp_blench_crye_knee",[["ACE_fieldDressing",8],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_tourniquet",2],["ACE_packingBandage",4],["ACE_elasticBandage",2]]],["tfa_v_mmac_teamleader_belt_coy",[["ACRE_PRC152",1],["ACRE_PRC343",1],["ACE_IR_Strobe_Item",4],["rhs_mag_m18_green",3,1],["rhs_mag_30Rnd_556x45_M855_Stanag_Pull_Tracer_Red",5,30],["1Rnd_SmokeBlue_Grenade_shell",3,1],["CUP_FlareYellow_M203",3,1],["UGL_FlareCIR_F",6,1],["ACE_40mm_Flare_red",8,1],["ACE_40mm_Flare_ir",4,1]]],["CUP_B_USPack_Coyote",[["ACRE_PRC117F",1],["ACRE_PRC343",1],["ACRE_PRC152",1],["1Rnd_SmokeRed_Grenade_shell",3,1],["CUP_1Rnd_HE_M203",3,1],["CUP_FlareRed_M203",4,1],["1Rnd_SmokeBlue_Grenade_shell",3,1]]],"SOTG_Helmets_8","G_Bandanna_khk",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","","ItemCompass","ItemWatch","USP_PVS31_BLK"]],[]]
                ],
                [
                    "Mid-Tech",
                    [[["CUP_arifle_L85A2_G","","","",["CUP_30Rnd_556x45_Stanag_L85",30],[],""],[],[],["QAC_CS95_DPM_DDPM_Rolled",[["kat_IFAK",1]]],["QAC_ECBA_PLCE_O_DDPM_DPM",[["ACRE_PRC343",1],["CUP_30Rnd_556x45_Stanag_L85_Tracer_Green",5,30],["vn_m18_red_mag",8,1]]],["A2BAFV2_bhawk_backpack_03_01",[["ACRE_PRC343",1],["ACRE_PRC152",1],["CUP_30Rnd_556x45_Stanag_L85_Tracer_Green",1,30],["vn_m18_green_mag",3,1],["vn_m18_red_mag",3,1]]],"A2BAF_V2_Helmet_06_DDPM","",["vn_mk21_binocs","","","",[],[],""],["ItemMap","","","vn_b_item_compass","vn_b_item_watch",""]],[]]
                ],
                [
                    "Vietnam",
                    [[["vn_m16_xm148","","","",["vn_m16_20_t_mag",18],["vn_40mm_m662_flare_r_mag",1],""],[],[],["vn_b_uniform_macv_05_01",[["vn_m18_green_mag",1,1],["vn_m16_20_t_mag",7,18]]],["vn_b_vest_usarmy_05",[["vn_m18_purple_mag",2,1],["vn_m18_yellow_mag",2,1],["vn_m18_green_mag",1,1]]],["vn_b_pack_lw_06",[["ACRE_PRC77",1],["kat_IFAK",1],["vn_40mm_m682_smoke_r_mag",5,1],["vn_m18_green_mag",1,1],["vn_m18_purple_mag",2,1],["vn_m18_red_mag",1,1]]],"vn_b_boonie_02_02","",["vn_m19_binocs_grn","","","",[],[],""],["vn_b_item_map","","","vn_b_item_compass","vn_b_item_watch",""]],[]]
                ],
                [
                    "WW2",
                    [[["SPE_M1A1_Thompson","","","",["SPE_30Rnd_Thompson_45ACP",30],[],""],[],["rhs_weap_rsp30_red","","","",["rhs_mag_rsp30_red",1],[],""],["U_SPE_US_CC_HBT_EM_roll",[["ACE_fieldDressing",4],["ACE_tourniquet",1],["ACE_morphine",1],["ACE_packingBandage",3],["SPE_30Rnd_Thompson_45ACP_t",2,30]]],["V_SPE_US_Vest_AB_early_2",[["kat_IFAK",1],["SPE_30Rnd_Thompson_45ACP_t",4,30],["SPE_US_M18_Violet",1,1],["SPE_US_M18_Yellow",2,1]]],["B_SPE_US_Radio_alt",[["SPE_US_M15",2,1],["SPE_US_M18_Red",4,1],["SPE_US_M18_Green",3,1],["SPE_US_M18_Violet",2,1]]],"H_SPE_US_Helmet_29ID_Scrim_os","",["SPE_Binocular_US","","","",[],[],""],["ItemMap","","","SPE_US_ItemCompass","SPE_US_ItemWatch",""]],[]]
                ]
            ]
        ]
    ]
];
