        [
            "ctbRhoBrokenWings",
            "CTB RHO BROKEN WINGS M3 2026 v4 kunduz valley BLUFOR",
            [
                [
                    "Platoon Leader",
                    [[[["ACWP_M4A5_145_troy_KAG_BLK_NET","acwp_rc1_net","WMLX_L_PEQ_T_IR_camo_tan","acwp_t2_net_g33_down",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],""]],[],[["acwp_glock19_black","","","",["ACWP_19Rnd_9x21_Mag_glock",19],[],""]],["Rho_RAR_Combat_shirt_Tucked",[["kat_IFAK",1]]],["TFB_AVS_Comms_1_152A",[["ACE_IR_Strobe_Item",1],["ACE_CableTie",2],["ACRE_PRC343",1],["ACRE_PRC152",1],["Karma_MosesPoleItem",1],["ACE_WaterBottle",2],["ItemAndroid",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1]],[["rhs_mag_an_m8hc",2,1],["ACE_M84",2,1],["ACWP_19Rnd_9x21_Mag_glock",2,19],["acex_intelitems_notepad",1,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",10,30],["rho_rar_handgrenade_f1",2,1]]],["ranger_pack_5",[]],"rho_rar_airframe_ir_bat_comtac_amcu","G_oak_2_cut",[],["ItemMap","","","ItemCompass","ItemWatch","USP_PVS31_WP_BLK2"]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "Platoon Medic",
                    [[[["ACWP_M4A5_105_troy_ROE_BLK_DON","acwp_rc1_tan_don","","acwp_eotech_don_g33_down",["ACWP_30rnd_556x45_EPR_PMAG_don",30],[],""]],[],[["acwp_glock19_black","","","",["ACWP_19Rnd_9x21_Mag_glock",19],[],""]],["Rho_RAR_Combat_shirt_Tucked",[["kat_IFAK",1]]],["TFB_JPC_Assaulter_13_152A",[["ACE_IR_Strobe_Item",1],["ACE_CableTie",2],["ACRE_PRC343",1],["ItemAndroid",1]],[["rhs_mag_an_m8hc",4,1],["ACE_M84",2,1],["ACWP_19Rnd_9x21_Mag_glock",2,19],["rhs_mag_30Rnd_556x45_M855A1_PMAG",10,30],["rho_rar_handgrenade_f1",2,1]]],["ranger_pack_5",[["ACE_salineIV",4],["ACE_salineIV_500",6],["ACE_splint",8],["ACE_suture",1],["kat_MFAK",1],["ACE_bodyBag",6],["KJW_MedicalExpansion_IV",1],["KJW_MedicalExpansion_SampleKit",4],["ACE_adenosine",2],["ACE_surgicalKit",1],["ACE_personalAidKit",1]]],"rho_rar_tw_exfil2025_comtac_ir_bat_scrim1","G_tweed_tacticool_weiss",[],["ItemMap","","","ItemCompass","ItemWatch","USP_PVS31_WP_TAR_MID_TAN"]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "JTAC",
                    [[[["ACWP_M4A5_145_7rail_GL_grip_don","acwp_rc1_don","M300_R_PEQ_T_IR_camo_don","rhsusf_acc_su230_mrds_c",["ACWP_30rnd_556x45_EPR_PMAG_don",30],["UGL_FlareCIR_F",1],""]],[],[["Worm_IZLIDB","","","",[],[],""]],["Rho_RAR_Combat_shirt_Tucked_Rolled",[["kat_IFAK",1]]],["TFB_AVS_Comms_3_MPU5",[["ACE_IR_Strobe_Item",1],["ACE_CableTie",2],["ACRE_PRC343",1],["ACRE_PRC152",1],["ItemcTab",1]],[["rhs_mag_an_m8hc",1,1],["ACE_M84",2,1],["Laserbatteries",2,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",10,30],["rho_rar_handgrenade_f1",2,1],["rhs_mag_M433_HEDP",10,1],["UGL_FlareCIR_F",3,1],["rhs_mag_m713_Red",2,1]]],["TFB_275_117G3",[["ACE_WaterBottle",1],["ACE_Flashlight_XL50",1],["ACRE_PRC117F",1]],[["acex_intelitems_notepad",1,1],["rhs_mag_m713_Red",8,1],["rhs_mag_m715_Green",4,1],["1Rnd_SmokeGreen_Grenade_shell",4,1],["1Rnd_SmokeBlue_Grenade_shell",4,1]]],"rho_rar_airframe_ir_bat_comtac_arc_amcu","rho_reconwrap_03_glasses_tan",[["Laserdesignator_01_khk_F","","","",[],[],""]],["ItemMap","B_UavTerminal","","ItemCompass","ItemWatch","USP_PVS31_WP_LOW_TAN"]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "Platoon Sergeant",
                    [[[["ACWP_M4A5_105_troy_AFG_BLK_TAN","acwp_rc1_tanp","WMLX_L_PEQ_T_IR_camo_tan","TOTT_t2_unity_blk",["ACWP_30rnd_556x45_EPR_PMAG_tan",30],[],""]],[],[["acwp_glock19_black","","","",["ACWP_19Rnd_9x21_Mag_glock",19],[],""]],["Rho_RAR_Combat_shirt_Tucked_Rolled",[["kat_IFAK",1]]],["TFB_AVS_Assaulter_15_MPU5",[["ACE_IR_Strobe_Item",1],["ACE_CableTie",2],["ACRE_PRC343",1],["ACRE_PRC152",1],["Karma_MosesPoleItem",1],["ACE_WaterBottle",2],["ItemAndroid",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1]],[["rhs_mag_an_m8hc",2,1],["ACE_M84",4,1],["ACWP_19Rnd_9x21_Mag_glock",2,19],["acex_intelitems_notepad",1,1],["ACWP_30rnd_556x45_EPR_PMAG_tan",10,30],["rho_rar_handgrenade_f1",4,1]]],[],"rho_rar_tw_exfil2025_comtac_ir_bat","G_oak_1_cut",[],["ItemMap","","","ItemCompass","ItemWatch","USP_PVS31_WP_TAR_HIGH_BLK2"]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "Section Commander",
                    [[[["ACWP_M4A5_105_troy_AFG_BLK_TAN","acwp_rc1_tanp","M620_R_PEQ_T_IR_camo_tan","TOTT_t2_unity_G33",["ACWP_30rnd_556x45_EPR_PMAG_tan",30],[],""]],[],[["acwp_glock19_black","","","",["ACWP_19Rnd_9x21_Mag_glock",19],[],""]],["Rho_RAR_Combat_shirt_Tucked_Rolled_MC_Gloves",[["kat_IFAK",1]]],["TFB_AVS_Comms_7_152A",[["ACE_IR_Strobe_Item",1],["ACE_CableTie",2],["ACRE_PRC343",1],["ACRE_PRC152",1],["Karma_MosesPoleItem",1],["ACE_WaterBottle",2],["ItemAndroid",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1]],[["rhs_mag_an_m8hc",2,1],["ACWP_19Rnd_9x21_Mag_glock",2,19],["acex_intelitems_notepad",1,1],["ACWP_30rnd_556x45_EPR_PMAG_tan",10,30],["rho_rar_handgrenade_f1",4,1],["tsp_flashbang_cts2",4,1]]],[],"rho_rar_airframe_ir_bat_comtac_arc_mc","rho_reconwrap_01_glasses",[],["ItemMap","","","ItemCompass","ItemWatch","USP_PVS31_WP_TAR_HIGH_BLK2"]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "Rifleman CFA",
                    [[[["ACWP_M4A5_145_ris_MOD3_don","acwp_rc1_cover_amcu","WMLX_L_PEQ_T_IR_camo_don","acwp_t2_don",["ACWP_30rnd_556x45_EPR_PMAG_don",30],[],""]],[],[["acwp_glock19_black","","","",["ACWP_19Rnd_9x21_Mag_glock",19],[],""]],["Rho_RAR_Combat_shirt_Tucked",[["kat_IFAK",1]]],["TFB_JPC_Assaulter_2_152A",[["ACE_IR_Strobe_Item",1],["ACE_CableTie",2],["ACRE_PRC343",1]],[["rhs_mag_an_m8hc",4,1],["ACWP_19Rnd_9x21_Mag_glock",2,19],["ACWP_30rnd_556x45_EPR_PMAG_don",10,30],["rho_rar_handgrenade_f1",3,1],["tsp_flashbang_cts2",4,1]]],["USMC_Backpack_TT_JPC",[["kat_MFAK",1]]],"rho_rar_airframe_ir_bat_amcu","G_Bandanna_oli",[],["ItemMap","","","ItemCompass","ItemWatch","USP_PVS31_WP_TAR_TAN2"]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "3: Rifleman (AT)",
                    [[[["ACWP_M4A5_105_troy_ROE_BLK_DON","acwp_rc1_cover_amcu","WMLX_L_PEQ_T_IR_camo_don","rhsusf_acc_su230_mrds_c",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],""]],[["rhs_weap_m72a7","","","",[],[],""]],[["acwp_glock19_black","","","",["ACWP_19Rnd_9x21_Mag_glock",19],[],""]],["Rho_RAR_Combat_shirt_Tucked",[["kat_IFAK",1]]],["TFB_JPC_Assaulter_13_152A",[["ACE_IR_Strobe_Item",1],["ACE_CableTie",2],["ACRE_PRC343",1],["ACE_WaterBottle",2]],[["rhs_mag_an_m8hc",1,1],["ACWP_19Rnd_9x21_Mag_glock",2,19],["rhs_mag_30Rnd_556x45_M855A1_PMAG",14,30],["rho_rar_handgrenade_f1",4,1],["tsp_flashbang_cts2",6,1]]],["TFB_275_JPCPACK1",[]],"rho_rar_airframe_ir_bat_comtac_mc","rho_reconwrap_mc_07_glasses",[],["ItemMap","","","ItemCompass","ItemWatch","USP_PVS31_WP_TAR_MID_BLK"]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "4: Autorifleman",
                    [[[["Tier1_M249_light_S_Desert","acwp_rc1_tan","Tier1_M249_LA5_M600V","rhsusf_acc_su230_mrds_c",["rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",200],[],""]],[],[["acwp_glock19_black","","","",["ACWP_19Rnd_9x21_Mag_glock",19],[],""]],["Rho_RAR_Combat_shirt_Tucked",[["kat_IFAK",1]]],["TFB_AVS_Weapons_5_152",[["ACE_IR_Strobe_Item",1],["ACE_CableTie",2],["ACRE_PRC343",1],["ACE_WaterBottle",2]],[["rhs_mag_an_m8hc",1,1],["rhs_mag_m67",2,1],["ACWP_19Rnd_9x21_Mag_glock",2,19],["rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",4,200],["tsp_flashbang_cts2",2,1]]],[],"rho_rar_airframe_ir_bat_comtac_amcu","rho_reconwrap_04_glasses",[],["ItemMap","","","ItemCompass","ItemWatch","USP_PVS31_WP_TAR_MID_BLK"]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "5: Grenadier",
                    [[[["ACWP_M4A5_145_7rail_GL_grip_net","acwp_rc1_cover_mc","Tier1_M4BII_NGAL_M600V","rhsusf_acc_su230_mrds_c",["ACWP_30rnd_556x45_EPR_PMAG_net",30],["rhs_mag_M433_HEDP",1],""]],[],[["ACWP_USP_TAN","","","",["ACWP_20Rnd_9x21_Mag_USP_TAN",20],[],""]],["Rho_RAR_Combat_shirt_Tucked",[["kat_IFAK",1]]],["TFB_AVS_Assaulter_2_152A",[],[["Tier1_30Rnd_556x45_M855A1_EMag",10,30],["ACWP_20Rnd_9x21_Mag_USP_TAN",2,20],["tsp_flashbang_cts2",4,1],["rho_rar_handgrenade_f1",2,1],["rhs_mag_M433_HEDP",16,1],["ACE_40mm_Flare_ir",4,1],["rhs_mag_m714_White",2,1]]],["TFB_275_AVS_Backpack",[]],"rho_rar_airframe_ir_bat_mc","G_tweed_tacticool_weiss",[],["ItemMap","","","ItemCompass","ItemWatch","USP_PVS31_WP_TAR_MID_BLK2"]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "Breacher",
                    [[[["ACWP_M4A5_145_troy_base_BLK_TAN","acwp_rc1_tanp","M620_L_PEQ_T_IR_camo_tan","tfb_unity_fast",["ACWP_30rnd_556x45_EPR_PMAG_tan",30],[],""]],[],[["acwp_glock19_black","","","",["ACWP_19Rnd_9x21_Mag_glock",19],[],""]],["Rho_RAR_Combat_shirt_Tucked_Rolled",[["kat_IFAK",1]]],["TFB_AVS_Assaulter_4_148",[["ACE_IR_Strobe_Item",1],["ACE_CableTie",2],["ACRE_PRC343",1],["ACE_M26_Clacker",1],["ACE_Flashlight_XL50",1],["ACE_DefusalKit",1],["tsp_breach_shock",1]],[["rhs_mag_an_m8hc",1,1],["ACWP_19Rnd_9x21_Mag_glock",2,19],["rho_rar_handgrenade_f1",4,1],["tsp_flashbang_cts2",4,1],["ACE_CTS9",2,1],["ACWP_30rnd_556x45_EPR_PMAG_tan",12,30]]],["ranger_pack_5",[["tsp_breach_shock",1]],[["DemoCharge_Remote_Mag",4,1],["tsp_breach_linear_mag",4,1],["tsp_breach_package_mag",2,1],["tsp_breach_stick_mag",2,1],["tsp_breach_popper_auto_mag",6,1],["tsp_breach_silhouette_mag",1,1]]],"rho_rar_tw_exfil2025_comtac_ir_bat_scrim3","rho_reconwrap_07_glasses",[],["ItemMap","","","ItemCompass","ItemWatch","USP_PVS31_WP_TAR_LOW_TAN"]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "Ammo Bearer (mk48)",
                    [[[["ACWP_M4A5_105_troy_AFG_BLK_DON","acwp_rc1_cover_amcu","WMLX_L_PEQ_T_IR_camo_don","rhsusf_acc_su230_mrds_c",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],""]],[["rhs_weap_m72a7","","","",[],[],""]],[["acwp_glock19_black","","","",["ACWP_19Rnd_9x21_Mag_glock",19],[],""]],["Rho_RAR_Combat_shirt_Tucked",[["kat_IFAK",1]]],["TFB_JPC_Assaulter_2_152A",[["ACE_IR_Strobe_Item",1],["ACE_CableTie",2],["ACRE_PRC343",1],["ACE_WaterBottle",2]],[["rhs_mag_an_m8hc",1,1],["ACWP_19Rnd_9x21_Mag_glock",2,19],["rho_rar_handgrenade_f1",4,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",14,30],["tsp_flashbang_cts2",6,1]]],["TFB_275_JPC_Backpack",[],[["ranger_100rnd_762_EPR",6,100]]],"rho_rar_airframe_ir_bat_mc","G_comba_2",[],["ItemMap","","","ItemCompass","ItemWatch","USP_PVS31_WP_TAR_MID_BLK"]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "Machine Gunner (mk48)",
                    [[[["75th_ranger_mk48","","75th_Ranger_sideMK48_LASER","75th_Eotech_EXPS3_up",["ranger_100rnd_762_EPR",100],[],""]],[],[["acwp_glock19_black","","","",["ACWP_19Rnd_9x21_Mag_glock",19],[],""]],["Rho_RAR_Combat_shirt_Tucked_Rolled",[["kat_IFAK",1]]],["TFB_AVS_Weapons_2_152A",[["ACE_IR_Strobe_Item",1],["ACE_CableTie",2],["ACRE_PRC343",1],["ACE_WaterBottle",2]],[["rhs_mag_an_m8hc",1,1],["rhs_mag_m67",2,1],["ACWP_19Rnd_9x21_Mag_glock",2,19],["ACE_SpareBarrel",1,1],["ranger_100rnd_762_EPR",5,100],["tsp_flashbang_cts2",2,1]]],[],"rho_rar_tw_exfil2025_comtac_ir_bat_scrim1","rho_reconwrap_01_glasses_tan",[],["ItemMap","","","ItemCompass","ItemWatch","USP_PVS31_WP_TAR_MID_BLK"]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "Ammo Bearer (240)",
                    [[[["ACWP_M4A5_105_troy_ROE_BLK_TAN","acwp_rc1_cover_amcu","WMLX_L_PEQ_T_IR_tan_camo_tan","rhsusf_acc_su230_mrds_c",["ACWP_30rnd_556x45_EPR_PMAG_tan",30],[],""]],[["rhs_weap_m72a7","","","",[],[],""]],[["acwp_glock19_black","","","",["ACWP_19Rnd_9x21_Mag_glock",19],[],""]],["Rho_RAR_Combat_shirt_Tucked",[["kat_IFAK",1]]],["TFB_JPC_Assaulter_13_152A",[["ACE_IR_Strobe_Item",1],["ACE_CableTie",2],["ACRE_PRC343",1],["ACE_WaterBottle",2]],[["rhs_mag_an_m8hc",1,1],["ACWP_19Rnd_9x21_Mag_glock",2,19],["rho_rar_handgrenade_f1",4,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",14,30],["tsp_flashbang_cts2",6,1]]],["TFB_275_JPC_Backpack",[],[["Tier1_100Rnd_762x51_Belt_M80A1_EPR",6,100]]],"rho_rar_airframe_ir_bat_comtac_amcu","rho_reconwrap_07_glasses_tan",[],["ItemMap","","","ItemCompass","ItemWatch","USP_PVS31_WP_TAR_MID_BLK"]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "Machine Gunner (240)",
                    [[[["75th_Ranger_m240L","","75th_Ranger_sideM240L_LASER","75th_SU230B",["Tier1_250Rnd_762x51_Belt_M80A1_EPR",250],[],""]],[],[["acwp_glock19_black","","","",["ACWP_19Rnd_9x21_Mag_glock",19],[],""]],["Rho_RAR_Combat_shirt_Tucked_Rolled",[["kat_IFAK",1]]],["TFB_AVS_Comms_6_MPU5",[["ACE_IR_Strobe_Item",1],["ACE_CableTie",2],["ACRE_PRC343",1],["ACE_WaterBottle",2]],[["rhs_mag_an_m8hc",1,1],["ACE_M84",2,1],["ACWP_19Rnd_9x21_Mag_glock",2,19],["ACE_SpareBarrel",1,1],["Tier1_250Rnd_762x51_Belt_M80A1_EPR",2,250],["Tier1_100Rnd_762x51_Belt_M80A1_EPR",1,100]]],[],"rho_rar_airframe_ir_bat_comtac_amcu","G_tweed_tacticool_weiss",[],["ItemMap","","","ItemCompass","ItemWatch","USP_PVS31_WP_TAR_MID_BLK"]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "Sniper A",
                    [[[["121_Geissele_MRGG_Paint","121_NIGHTOWL_PAINT","121_USASOC_STORM_SLX_Paint_Laser","121_USASOC_RVPS_ANPVS30_PAINT",["121_pmag_paint_65_Creedmoor_20rnd",20],[],""]],[],[["acwp_glock19_black","","","",["ACWP_19Rnd_9x21_Mag_glock",19],[],""]],["Rho_RAR_Combat_shirt_Tucked",[["kat_IFAK",1]]],["TFB_AVS_Light_2_152A",[["ACE_IR_Strobe_Item",1],["ACE_CableTie",2],["ACRE_PRC343",1],["ACE_WaterBottle",2]],[["rhs_mag_an_m8hc",1,1],["ACE_M84",6,1],["ACWP_19Rnd_9x21_Mag_glock",4,19],["rho_rar_handgrenade_f1",4,1],["121_pmag_paint_65_Creedmoor_20rnd",10,20]]],["TFB_275_JPCPACK1",[],[["121_pmag_paint_65_Creedmoor_20rnd",4,20]]],"rho_rar_tw_exfil2025_comtac_ir_bat","rho_reconwrap_01_glasses_tan",[["ACE_MX2A","","","",[],[],""]],["ItemMap","","","ItemCompass","ItemWatch","USP_PVS31_WP_TAR_MID_BLK"]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "Sniper B",
                    [[[["121_Geissele_MRGG_Paint","121_NIGHTOWL_PAINT","121_USASOC_Raptar_Paint_Laser","121_USASOC_RVPS_ANPVS30_PAINT",["121_pmag_paint_65_Creedmoor_20rnd",20],[],""]],[],[["acwp_glock19_black","","","",["ACWP_19Rnd_9x21_Mag_glock",19],[],""]],["Rho_RAR_Combat_shirt_Tucked_Rolled",[["kat_IFAK",1]]],["TFB_AVS_Assaulter_4_148",[["ACE_IR_Strobe_Item",1],["ACE_CableTie",2],["ACRE_PRC343",1],["ACE_M26_Clacker",1],["ACE_Flashlight_XL50",1],["ACE_DefusalKit",1],["tsp_breach_shock",1]],[["rhs_mag_an_m8hc",1,1],["ACE_M84",2,1],["ACWP_19Rnd_9x21_Mag_glock",2,19],["rho_rar_handgrenade_f1",2,1],["tsp_flashbang_cts2",2,1],["ACE_CTS9",2,1],["121_pmag_paint_65_Creedmoor_20rnd",12,20]]],["ranger_pack_5",[["121_tripod_item",1]],[["DemoCharge_Remote_Mag",4,1],["tsp_breach_linear_mag",4,1],["tsp_breach_package_mag",2,1],["tsp_breach_stick_mag",2,1],["tsp_breach_popper_auto_mag",6,1],["121_pmag_paint_65_Creedmoor_20rnd",4,20]]],"rho_rar_tw_exfil2025_comtac_ir_bat_scrim3","rho_reconwrap_07_glasses",[["121_spotting_scope_handheld","","","",[],[],""]],["ItemMap","","","ItemCompass","ItemWatch","USP_PVS31_WP_TAR_LOW_TAN"]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "Pilot",
                    [[[["rhs_weap_mk18_urgi_kac","rhsusf_acc_SF3P556_hidden","Tier1_Mk18_NGAL_M300C","TOTT_XPS3",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],""]],[],[["acwp_glock19_black","","","",["ACWP_19Rnd_9x21_Mag_glock",19],[],""]],["SOAR_Flight_4_uniform",[["kat_IFAK",1]]],["AVS_Flight_5_Water",[["ACRE_PRC343",1],["ACRE_PRC152",1],["ItemAndroid",1],["ACE_Chemlight_IR",2],["ACE_Chemlight_HiBlue",1],["ACE_Chemlight_HiGreen",1],["ACE_WaterBottle",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1]],[["ACWP_19Rnd_9x21_Mag_glock",2,19],["rhs_mag_30Rnd_556x45_M855A1_Stanag",4,30],["SmokeShellOrange",1,1],["SmokeShellBlue",1,1],["SmokeShellPurple",1,1],["SmokeShellGreen",1,1],["rhs_mag_m67",1,1]]],[],"rhsusf_hgu56p_mask","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","USMC_Anvis"]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "Co-Pilot",
                    [[[["rhs_weap_mk18_urgi_kac","rhsusf_acc_SF3P556_hidden","Tier1_Mk18_NGAL_M600V_Black_FL","TOTT_XPS3",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],""]],[],[["acwp_glock19_black","","","",["ACWP_19Rnd_9x21_Mag_glock",19],[],""]],["SOAR_Flight_4_uniform",[["kat_IFAK",1]]],["AVS_Flight_7_Water",[["ACRE_PRC343",1],["ACRE_PRC152",1],["ItemAndroid",1],["ACE_Chemlight_IR",2],["ACE_Chemlight_HiBlue",1],["ACE_Chemlight_HiGreen",1],["ACE_WaterBottle",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1]],[["ACWP_19Rnd_9x21_Mag_glock",2,19],["rhs_mag_30Rnd_556x45_M855A1_Stanag",4,30],["SmokeShellOrange",1,1],["SmokeShellBlue",1,1],["SmokeShellPurple",1,1],["SmokeShellGreen",1,1],["rhs_mag_m67",1,1]]],[],"rhsusf_hgu56p","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","USMC_Anvis"]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "Crew Chief",
                    [[[["rhs_weap_mk18_urgi_kac","rhsusf_acc_SF3P556_hidden","Tier1_Mk18_NGAL_M300C_Black","TOTT_XPS3",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],""]],[],[["acwp_glock19_black","","","",["ACWP_19Rnd_9x21_Mag_glock",19],[],""]],["SOAR_Flight_9_uniform",[["kat_IFAK",1]]],["AVS_Flight_6_Water",[["ACRE_PRC343",1],["ACRE_PRC152",1],["ItemAndroid",1],["ACE_Chemlight_IR",2],["ACE_Chemlight_HiBlue",1],["ACE_Chemlight_HiGreen",1],["ACE_WaterBottle",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1]],[["ACWP_19Rnd_9x21_Mag_glock",2,19],["rhs_mag_30Rnd_556x45_M855A1_Stanag",6,30],["SmokeShellOrange",1,1],["SmokeShellBlue",1,1],["SmokeShellPurple",1,1],["SmokeShellGreen",1,1],["rhs_mag_m67",1,1]]],[],"rhsusf_hgu56p_mask_mo","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","USMC_Anvis"]],[["aceax_textureOptions",[]]]]
                ],
                [
                    "Crew",
                    [[[["rhs_weap_mk18_urgi_kac","rhsusf_acc_SF3P556_hidden","Tier1_Mk18_NGAL_M300C","TOTT_XPS3",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],""]],[],[["acwp_glock19_black","","","",["ACWP_19Rnd_9x21_Mag_glock",19],[],""]],["SOAR_Flight_4_uniform",[["kat_IFAK",1]]],["AVS_Flight_4_Water",[["ACRE_PRC343",1],["ACRE_PRC152",1],["ItemAndroid",1],["ACE_Chemlight_IR",2],["ACE_Chemlight_HiBlue",1],["ACE_Chemlight_HiGreen",1],["ACE_WaterBottle",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1]],[["ACWP_19Rnd_9x21_Mag_glock",2,19],["rhs_mag_30Rnd_556x45_M855A1_Stanag",4,30],["SmokeShellOrange",1,1],["SmokeShellBlue",1,1],["SmokeShellPurple",1,1],["SmokeShellGreen",1,1],["rhs_mag_m67",2,1]]],[],"rhsusf_hgu56p_mask","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","USMC_Anvis"]],[["aceax_textureOptions",[]]]]
                ],
            ]
        ]